version: "3"

services:
  backend:
    restart: always
    command: ["./start_gunicorn.sh"]

  redis:
    restart: always

  rabbitmq:
    restart: always

  backend-worker:
    restart: always
    command: dramatiq litmapper.tasks:broker litmapper

  database:
    restart: always

  frontend:
    # We need this service/image built so we can use it to build the deployment artifacts,
    # but we don't want it running by default -- "disable" it by changing the entrypoint
    # to one that does nothing and disable restart policy
    restart: "no"
    entrypoint: ["echo", "'Service disabled in production.'"]

  frontend-static:
    image: "epa-litmapper-frontend-static:${IMAGE_TAG:-latest}"
    build:
      context: ./frontend/
      dockerfile: ./deploy/Dockerfile
    ports:
      - "${LITMAPPER_FRONTEND_PORT:-8080}:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf

  specter:
    restart: always

  specter_database:
    restart: always
