name: CI

on:
  push:
    branches: [main]
    # Only on these paths so that something like a README update doesn't trigger it
    paths:
      - requirements.txt
      - "**.py"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - requirements.txt
      - "**.py"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint backend code
        run: ./scripts/lint_backend.sh

  lint_etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint ETL code
        run: ./scripts/lint_etl.sh

  lint_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint frontend code
        run: ./scripts/lint_frontend.sh

  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start database services
        run: docker compose up -d database redis
      - name: Wait for database startup to finish
        run: sleep 10s
        shell: bash
      - name: Run backend tests
        run: ./scripts/test_backend.sh
